#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jackson-dataformats-text
Version  : 2.9.9
Release  : 2
URL      : https://github.com/FasterXML/jackson-dataformats-text/archive/jackson-dataformats-text-2.9.9.tar.gz
Source0  : https://github.com/FasterXML/jackson-dataformats-text/archive/jackson-dataformats-text-2.9.9.tar.gz
Source1  : https://repo1.maven.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-csv/2.9.9/jackson-dataformat-csv-2.9.9.jar
Source2  : https://repo1.maven.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-csv/2.9.9/jackson-dataformat-csv-2.9.9.pom
Source3  : https://repo1.maven.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformats-text/2.9.9/jackson-dataformats-text-2.9.9.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-jackson-dataformats-text-data = %{version}-%{release}
Requires: mvn-jackson-dataformats-text-license = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
## Overview
This is a multi-module umbrella project for [Jackson](../../../jackson)
standard text-format dataformat backends.

%package data
Summary: data components for the mvn-jackson-dataformats-text package.
Group: Data

%description data
data components for the mvn-jackson-dataformats-text package.


%package license
Summary: license components for the mvn-jackson-dataformats-text package.
Group: Default

%description license
license components for the mvn-jackson-dataformats-text package.


%prep
%setup -q -n jackson-dataformats-text-jackson-dataformats-text-2.9.9

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-jackson-dataformats-text
cp properties/src/main/resources/META-INF/LICENSE %{buildroot}/usr/share/package-licenses/mvn-jackson-dataformats-text/properties_src_main_resources_META-INF_LICENSE
cp yaml/src/main/resources/META-INF/LICENSE %{buildroot}/usr/share/package-licenses/mvn-jackson-dataformats-text/yaml_src_main_resources_META-INF_LICENSE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-csv/2.9.9
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-csv/2.9.9/jackson-dataformat-csv-2.9.9.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-csv/2.9.9
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-csv/2.9.9/jackson-dataformat-csv-2.9.9.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformats-text/2.9.9
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformats-text/2.9.9/jackson-dataformats-text-2.9.9.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-csv/2.9.9/jackson-dataformat-csv-2.9.9.jar
/usr/share/java/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-csv/2.9.9/jackson-dataformat-csv-2.9.9.pom
/usr/share/java/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformats-text/2.9.9/jackson-dataformats-text-2.9.9.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-jackson-dataformats-text/properties_src_main_resources_META-INF_LICENSE
/usr/share/package-licenses/mvn-jackson-dataformats-text/yaml_src_main_resources_META-INF_LICENSE
